server:
  port: 8200
eureka:
  client:
    service-url:
      fetch-registry: true
      default-zone: http://localhost:8761/eureka
spring:
  application:
    name: currency-service
  sleuth:
    sampler:
      probability: 1.0
zipkin:
  collector:
    kafka:
      bootstrap-servers: localhost:9092
scheduler:
  cron: "0 0/1 * * * *"
kafka:
  bootstrapAddress: localhost:9092
  topics:
    currency-update: currency-update
currency:
  from: USD
  to: BRL, GBP, ARS, EUR, COP, MXN, CLP