server:
  port: 8000
spring:
  application:
    name: exchange-service

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exchange?useTimezone=true&serverTimeZone=UTC
    username: exchange
    password: exchange
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306/
    user: exchange
    password: exchange
    schemas: exchange