server:
  port: 8100
spring:
  application:
    name: book-service

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/book?useTimezone=true&serverTimeZone=UTC
    username: book
    password: book
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3307/
    user: book
    password: book
    schemas: book

  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non_null