version: "3"

services:
  exchange-db:
    image: mysql
    container_name: exchange-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
      - local-dev
    restart: on-failure
    environment:
#      MYSQL_DATABASE: "exchange"
      MYSQL_USER: "exchange"
      MYSQL_PASSWORD: "exchange"
      MYSQL_ROOT_PASSWORD : "root"
    volumes:
      - ./volumes/exchange-db:/var/lib/mysql
      - ./init/init-exchange.sql:/docker-entrypoint-initdb.d/init.sql
  book-db:
    image: mysql
    container_name: book-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    networks:
      - local-dev
    restart: on-failure
    environment:
#      MYSQL_DATABASE: "book"
      MYSQL_USER: "book"
      MYSQL_PASSWORD: "book"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./volumes/book-db:/var/lib/mysql
      - ./init/init-book.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  local-dev:
    driver: bridge